# Generated by Django 3.0.3 on 2020-12-04 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_project_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='thumbnail',
            new_name='thumbnail_screen_lg',
        ),
        migrations.AddField(
            model_name='project',
            name='thumbnail_screen_sm',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
