# Generated by Django 3.0.3 on 2020-12-13 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_file_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
