# Generated by Django 3.0.3 on 2021-01-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20210127_1506'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachlist',
            options={'ordering': ['-date_added'], 'verbose_name_plural': 'teacheslist'},
        ),
        migrations.AddField(
            model_name='teachlist',
            name='slug',
            field=models.SlugField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
