# Generated by Django 3.0.3 on 2021-01-27 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20210127_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='teach',
        ),
        migrations.DeleteModel(
            name='TeachList',
        ),
    ]
