# Generated by Django 3.0.3 on 2021-02-07 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20210206_1202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teach',
            options={'verbose_name_plural': 'teaches'},
        ),
        migrations.AddField(
            model_name='teach',
            name='thumbnail',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
